//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TauseelRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_T
    {
        public int MenuID { get; set; }
        public Nullable<int> MenuTypeID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string Menu { get; set; }
        public string Description { get; set; }
        public Nullable<bool> PriceUponSelection { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> Offer { get; set; }
    
        public virtual MenuType_T MenuType_T { get; set; }
        public virtual Shop_T Shop_T { get; set; }
    }
}
