//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TauseelRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail_T
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Menu { get; set; }
        public string Description { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Order_T Order_T { get; set; }
    }
}
