//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TauseelRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating_T
    {
        public int RatingID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Rating { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    
        public virtual ResCustomer_T ResCustomer_T { get; set; }
    }
}
