//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TauseelRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResCustomer_T
    {
        public ResCustomer_T()
        {
            this.Rating_T = new HashSet<Rating_T>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string FlatVilla { get; set; }
        public string Building { get; set; }
        public string Road { get; set; }
        public string Block { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public string Landmark { get; set; }
        public Nullable<int> MainCustomerID { get; set; }
    
        public virtual ICollection<Rating_T> Rating_T { get; set; }
    }
}
