//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TauseelRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rider_T
    {
        public int RID { get; set; }
        public string RFName { get; set; }
        public string RLName { get; set; }
        public string REmailAddress { get; set; }
        public string RMobileType { get; set; }
        public string RContactNo { get; set; }
        public string RAddress { get; set; }
        public string RIDProofType { get; set; }
        public string RIDProofNo { get; set; }
        public string RVehicleType { get; set; }
        public string RVehicleRegistrationNo { get; set; }
        public string RDrivingLicenseNo { get; set; }
        public Nullable<System.DateTime> RRegistrationDate { get; set; }
        public Nullable<System.DateTime> RLastSync { get; set; }
        public string RUserDeviceRegId { get; set; }
    }
}
