//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TauseelRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_T
    {
        public Status_T()
        {
            this.Order_T = new HashSet<Order_T>();
            this.Order_T1 = new HashSet<Order_T>();
        }
    
        public int StatusID { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Order_T> Order_T { get; set; }
        public virtual ICollection<Order_T> Order_T1 { get; set; }
    }
}
