//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TauseelRestaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TauseelEatEntities : DbContext
    {
        public TauseelEatEntities()
            : base("name=TauseelEatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Menu_T> Menu_T { get; set; }
        public DbSet<Menu_MenuSubItemGroup_T> Menu_MenuSubItemGroup_T { get; set; }
        public DbSet<MenuSubItem_T> MenuSubItem_T { get; set; }
        public DbSet<MenuSubItemGroup_T> MenuSubItemGroup_T { get; set; }
        public DbSet<MenuType_T> MenuType_T { get; set; }
        public DbSet<Order_T> Order_T { get; set; }
        public DbSet<OrderDetail_T> OrderDetail_T { get; set; }
        public DbSet<Rating_T> Rating_T { get; set; }
        public DbSet<ResCustomer_T> ResCustomer_T { get; set; }
        public DbSet<Shop_T> Shop_T { get; set; }
        public DbSet<ShopCuisine_T> ShopCuisine_T { get; set; }
        public DbSet<ShopLocation_T> ShopLocation_T { get; set; }
        public DbSet<ShopTiming_T> ShopTiming_T { get; set; }
        public DbSet<Status_T> Status_T { get; set; }
        public DbSet<Category_T> Category_T { get; set; }
        public DbSet<Cuisine_T> Cuisine_T { get; set; }
        public DbSet<Location_T> Location_T { get; set; }
        public DbSet<ShopMapping_T> ShopMapping_T { get; set; }
        public DbSet<DeliveryPersonLocation_T> DeliveryPersonLocation_T { get; set; }
        public DbSet<Rider_T> Rider_T { get; set; }
    
        public virtual int delCustomer(Nullable<int> customerid)
        {
            var customeridParameter = customerid.HasValue ?
                new ObjectParameter("customerid", customerid) :
                new ObjectParameter("customerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCustomer", customeridParameter);
        }
    
        public virtual int delShop(Nullable<int> shopid)
        {
            var shopidParameter = shopid.HasValue ?
                new ObjectParameter("shopid", shopid) :
                new ObjectParameter("shopid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delShop", shopidParameter);
        }
    }
}
